#!/bin/bash

git clone https://github.com/yousefafc/go-boot

docker build .
docker push yousefafc/golang

if docker ps | grep golang
then
	echo "exists"
	docker stop golang
	docker rm golang
	docker run -d -p 8080:8080 --name golang golang
else
	echo "doesn't exist"
	docker run -d -p 8080:8080 --name golang golang
fi
